//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistantFallDetector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssistantFallDetector.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Fall Detector.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string ContactDetailsAccountsText {
            get {
                return ResourceManager.GetString("ContactDetailsAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company information.
        /// </summary>
        public static string ContactDetailsCompanyInformationText {
            get {
                return ResourceManager.GetString("ContactDetailsCompanyInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite number.
        /// </summary>
        public static string ContactDetailsPageDialogCaption {
            get {
                return ResourceManager.GetString("ContactDetailsPageDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string ContactDetailsPageDialogLeftButtonText {
            get {
                return ResourceManager.GetString("ContactDetailsPageDialogLeftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number.
        /// </summary>
        public static string ContactDetailsPageDialogMessage1 {
            get {
                return ResourceManager.GetString("ContactDetailsPageDialogMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the selected contact.
        /// </summary>
        public static string ContactDetailsPageDialogMessage2 {
            get {
                return ResourceManager.GetString("ContactDetailsPageDialogMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been added to send alarm notifications..
        /// </summary>
        public static string ContactDetailsPageDialogMessage3 {
            get {
                return ResourceManager.GetString("ContactDetailsPageDialogMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email addresses.
        /// </summary>
        public static string ContactDetailsPageEmailsAddressesText {
            get {
                return ResourceManager.GetString("ContactDetailsPageEmailsAddressesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone numbers.
        /// </summary>
        public static string ContactDetailsPagePhoneNumbersText {
            get {
                return ResourceManager.GetString("ContactDetailsPagePhoneNumbersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact details.
        /// </summary>
        public static string ContactDetailsPageTitleText {
            get {
                return ResourceManager.GetString("ContactDetailsPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web sites.
        /// </summary>
        public static string ContactDetailsPageWebSitesText {
            get {
                return ResourceManager.GetString("ContactDetailsPageWebSitesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration maximum reached (G).
        /// </summary>
        public static string MainPageAccelerometerAccelerationMaxText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerAccelerationMaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceleration (G).
        /// </summary>
        public static string MainPageAccelerometerAccelerationText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerAccelerationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recognition phase alarm.
        /// </summary>
        public static string MainPageAccelerometerStateAlarmText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerStateAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string MainPageAccelerometerStateAlarmText1 {
            get {
                return ResourceManager.GetString("MainPageAccelerometerStateAlarmText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threshold reached.
        /// </summary>
        public static string MainPageAccelerometerStateAlarmText2 {
            get {
                return ResourceManager.GetString("MainPageAccelerometerStateAlarmText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idle time finished.
        /// </summary>
        public static string MainPageAccelerometerStateAlarmText3 {
            get {
                return ResourceManager.GetString("MainPageAccelerometerStateAlarmText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string MainPageAccelerometerStatusText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time between updates (ms).
        /// </summary>
        public static string MainPageAccelerometerTimeUpdatesText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerTimeUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerometer.
        /// </summary>
        public static string MainPageAccelerometerTitleText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis (G).
        /// </summary>
        public static string MainPageAccelerometerXAxisText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerXAxisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis (G).
        /// </summary>
        public static string MainPageAccelerometerYAxisText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerYAxisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Axis (G).
        /// </summary>
        public static string MainPageAccelerometerZAxisText {
            get {
                return ResourceManager.GetString("MainPageAccelerometerZAxisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string MainPageAppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPageAppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string MainPageContactsEmailFilterText {
            get {
                return ResourceManager.GetString("MainPageContactsEmailFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results are loading....
        /// </summary>
        public static string MainPageContactsLoadingLabelText1 {
            get {
                return ResourceManager.GetString("MainPageContactsLoadingLabelText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results (tap name for details...).
        /// </summary>
        public static string MainPageContactsLoadingLabelText2 {
            get {
                return ResourceManager.GetString("MainPageContactsLoadingLabelText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no results.
        /// </summary>
        public static string MainPageContactsLoadingLabelText3 {
            get {
                return ResourceManager.GetString("MainPageContactsLoadingLabelText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string MainPageContactsNameFilterText {
            get {
                return ResourceManager.GetString("MainPageContactsNameFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string MainPageContactsPhoneFilterText {
            get {
                return ResourceManager.GetString("MainPageContactsPhoneFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for contacts.
        /// </summary>
        public static string MainPageContactsResultsLabelText {
            get {
                return ResourceManager.GetString("MainPageContactsResultsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageContactsSearchFilterText {
            get {
                return ResourceManager.GetString("MainPageContactsSearchFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string MainPageContactsTitleText {
            get {
                return ResourceManager.GetString("MainPageContactsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKGROUND GPS.
        /// </summary>
        public static string MainPageLocationGPSBckgTitleText {
            get {
                return ResourceManager.GetString("MainPageLocationGPSBckgTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string MainPageLocationTitleText {
            get {
                return ResourceManager.GetString("MainPageLocationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ack.
        /// </summary>
        public static string MainPagePopupAckButtonText {
            get {
                return ResourceManager.GetString("MainPagePopupAckButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the alarm threshold has been exceeded!.
        /// </summary>
        public static string MainPagePopupDescriptionText {
            get {
                return ResourceManager.GetString("MainPagePopupDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send notification.
        /// </summary>
        public static string MainPagePopupSendNotificationButtonText {
            get {
                return ResourceManager.GetString("MainPagePopupSendNotificationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MainPagePopupTitleText {
            get {
                return ResourceManager.GetString("MainPagePopupTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration alarm (G).
        /// </summary>
        public static string MainPageSettingsAccelerationAlarmText {
            get {
                return ResourceManager.GetString("MainPageSettingsAccelerationAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accelerometer.
        /// </summary>
        public static string MainPageSettingsAccelerometerModeText {
            get {
                return ResourceManager.GetString("MainPageSettingsAccelerometerModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time idle to launch the notification (ms).
        /// </summary>
        public static string MainPageSettingsIdleTimeAccelerationAlarmText {
            get {
                return ResourceManager.GetString("MainPageSettingsIdleTimeAccelerationAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number of favorite contact.
        /// </summary>
        public static string MainPageSettingsPhoneNumberFavoriteContactText {
            get {
                return ResourceManager.GetString("MainPageSettingsPhoneNumberFavoriteContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPageSettingsTitleText {
            get {
                return ResourceManager.GetString("MainPageSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi.
        /// </summary>
        public static string MainPageSettingsWifiText {
            get {
                return ResourceManager.GetString("MainPageSettingsWifiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm threshold has been exceeded.
        /// </summary>
        public static string NotificationAlarmText {
            get {
                return ResourceManager.GetString("NotificationAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
